### ISSUE TITLE
Renewal of a wildcard certificate fails

### ISSUE THREAD

**Issue by kostich** [robin-thoni/certbot-pdns#4]
Using the latest certbot and certbot-pdns. Tried both Python2 and Python3 modules. Command used to renew the certificate:

> certbot --agree-tos --text --renew-by-default --server https://acme-v02.api.letsencrypt.org/directory --authenticator certbot-pdns:auth -m something@domain.eu -d *.something.domain.eu renew

Traceback:

```
Cleaning up challenges
Encountered exception during recovery
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/usr/local/lib/python3.5/dist-packages/certbot/auth_handler.py", line 303, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/local/lib/python3.5/dist-packages/certbot_pdns/authenticator.py", line 72, in cleanup
    self.backend.cleanup(achall)
  File "/usr/local/lib/python3.5/dist-packages/certbot_pdns/PdnsApiAuthenticator.py", line 101, in cleanup
    res = self.api.delete_record(zone["name"], "_acme-challenge." + domain + ".", "TXT", 1, None, False, False)
  File "/usr/local/lib/python3.5/dist-packages/certbot_pdns/pdnsapi.py", line 77, in delete_record
    "set-prt": set_ptr
  File "/usr/local/lib/python3.5/dist-packages/certbot_pdns/pdnsapi.py", line 38, in _query
    return None if request.status_code == 204 else request.json()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
 
Seems that the requests Response object returned doesn't contain an .json() method which decodes properly.

I've experimented a bit and if you replace line 38 (in certbot_pdns/pdnsapi.py):

> return None if request.status_code == 204 else request.json()

with:

> return None if request.status_code == 204  or request.status_code == 400 else request.json()

you can workaround this issue and renew the wildcard certificate.

**Comment by kostich** [comment]
Seems that the issue was caused by my http proxy. I've prefixed the command with `http_proxy=""` and the renewal works as intended.

Closing this issue.

**Comment by robin-thoni** [comment]
I'm glad you resolved your issue. Although it's not a certbot-pdns direct issue, this indicates a lack of error handling in the code that would need to be fixed...
