### ISSUE TITLE
Can't issue wildcard certificates

### ISSUE THREAD

**Issue by Zoddo** [robin-thoni/certbot-pdns#5]
Hey,

When I try to issue a wildcard certificate with certbot and this plugin, the plugin crash as follow:

```
$ sudo certbot --authenticator certbot-pdns:auth --cert-name phpbb-fr.com -d domain.com,*.domain.com --server https://acme-v02.api.letsencrypt.org/directory
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-pdns:auth, Installer apache
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for domain.com
dns-01 challenge for domain.com
Cleaning up challenges
Encountered exception during recovery
Bad return from PDNS API when deleting record: {u'error': u'Internal Server Error'}
Traceback (most recent call last):
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/error_handler.py", line 103, in _call_registered
    self.funcs[-1]()
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot/auth_handler.py", line 308, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_pdns/authenticator.py", line 72, in cleanup
    self.backend.cleanup(achall)
  File "/opt/eff.org/certbot/venv/local/lib/python2.7/site-packages/certbot_pdns/PdnsApiAuthenticator.py", line 103, in cleanup
    raise errors.PluginError("Bad return from PDNS API when deleting record: %s" % res)
PluginError: Bad return from PDNS API when deleting record: {u'error': u'Internal Server Error'}
Bad return from PDNS API when adding record: {u'error': u'Internal Server Error'}
```

certbot 0.23.0

**Comment by Zoddo** [comment]
Sorry, I didn't checked correctly my logs 😐 

It was an issue with the PDNS backend, so it's totally unrelated to this plugin.
